[project]
name = "python-asyncio-poc"
version = "0.1.0"
description = "Asyncio POC with uv"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx",
    "fastapi",
    "uvicorn",
]
